const Map<String, String> formulaImages = {
  "Alfamino Infant": "assets/can_images/alfamino_infant.png",
  "Elecare Infant": "assets/can_images/elecare_infant.png",
  "Enfacare": "assets/can_images/enfacare.png",
  "Enfamil AR": "assets/can_images/enfamil_AR.png",
  "Enfamil Gentlease": "assets/can_images/enfamil_gentlease.png",
  "Enfamil NeuroPro Infant": "assets/can_images/enfamil_neuropro.png",
  "Enfaport": "assets/can_images/enfaport(1).png",
  "Extensive HA": "assets/can_images/extensive_HA.png",
  "Fortini": "assets/can_images/fortini.png",
  "Gerber Good Start Gentle": "assets/can_images/gerber_goodstart_gentle.png",
  "Gerber Good Start Soothe": "assets/can_images/gerber_goodstart_soothe.png",
  "Monogen": "assets/can_images/monogen.png",
  "Neocate Infant": "assets/can_images/neocate_infant.png",
  "Neosure": "assets/can_images/neosure.png",
  "Nutramigen": "assets/can_images/nutramigen.png",
  "Pepticate": "assets/can_images/pepticate.png",
  "Pregestimil": "assets/can_images/pregestimil.png",
  "Prosobee": "assets/can_images/enfamil_prosobee.png",
  "PurAmino": "assets/can_images/puramino.png",
  "Similac Advance": "assets/can_images/similac_advance.png",
  "Similac Alimentum": "assets/can_images/similac_alimentum.png",
  "Similac Human Milk Fortifier": "assets/can_images/similac_hmf.png",
  "Similac PM 60/40": "assets/can_images/PM_6040.png",
  "Similac Pure Bliss": "assets/can_images/pure_bliss.png",
  "Similac Sensitive": "assets/can_images/similac_sensitive.png",
  "Similac Soy Isomil": "assets/can_images/similac_soy_isomil.png",
  "Similac Special Care Blends": "assets/can_images/similac_special_care.png",
  "Similac Total Comfort": "assets/can_images/similac_total_comfort.png",
};

const Map<String, String> additiveImages = {
  "Oatmeal": "assets/can_images/oatmeal.png",
  "Gelmix": "assets/can_images/gelmix.png",
};
